function preload() {
  spriteGameBackground = loadImage("src/assets/Ruined_City_Background.png");
  spriteTennisball = loadImage("src/assets/Tennisball.png");
  spriteFlatDog = loadImage("src/assets/Flat_Dog.png");
  spriteSuperDog = loadImage("src/assets/Super_Dog.png");
  spriteSuperDog2 = loadImage("src/assets/SuperDog2.png");
  spriteBlock1 = loadImage("src/assets/1.png");
  spriteBlock2 = loadImage("src/assets/2.png");
  spriteBlock3 = loadImage("src/assets/3.png");
  spriteBlock4 = loadImage("src/assets/4.png");
  spriteBlock5 = loadImage("src/assets/5.png");
  spriteBlock6 = loadImage("src/assets/6.png");
  spriteBlock7 = loadImage("src/assets/7.png");
  spriteXLife = loadImage("src/assets/tile001.png");
  spriteDouble = loadImage("src/assets/tile007.png");
  spriteMagnet = loadImage("src/assets/tile008.png");
  spriteBeamPot = loadImage("src/assets/tile006.png");
  spriteDropParty = loadImage("src/assets/tile010.png");
}
